Development/invapp/config/routes.rb
Rails.application.routes.draw do
  get '/incidents', controller: :incidents, action: :index, as: :incidents
  delete 'incidents', controller: :incidents, action: :clear
  
  root 'home#index'
  resources :inventories
  resources :products
  resources :categories
  resources :warehouses
  resources :products

end

Development/invapp/app/models/incident.rb
class Incident < ActiveRecord::Base
  def self.log(target, messages)
    messages.each do |message|
      Incident.create(target: target, message: message)
    end
  end
  def self.clear_log
    Incident.delete_all
  end
end

Development/invapp/app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  def index
    @incidents = Incident.all.order(created_at: :desc)
  end
  
  def clear
    Incident.clear_log
    redirect_to root_url
  end
end

Development/invapp/app/helpers/incidents_helper.rb
module IncidentsHelper
end

Development/invapp/app/views/incidents/index.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Validation " + model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:logged_at) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:target) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      
    </tr>
  </thead>
  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%=l incident.created_at %></td>
        <td><%= incident.id %></td>
        <td><%= incident.target %></td>
        <td><%= incident.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Clear Log', incidents_path, method: :delete, class: 'btn btn-primary' %>